### ISSUE TITLE
Single top + Z datasets with bad SM_best/SM_LO

### ISSUE THREAD

**Issue by LucaMantani** [LHCfitNikhef/smefit_database#2]
The datasets [CMS_tZ_13TeV_inc.json](https://github.com/LHCfitNikhef/smefit_database/blob/main/theory/CMS_tZ_13TeV_inc.json) and [CMS_tZ_13TeV_2016_inc.json](https://github.com/LHCfitNikhef/smefit_database/blob/main/theory/CMS_tZ_13TeV_2016_inc.json) have a bad ratio of SM_best and the LO SM. I believe it's because the SM LO is missing a factor of 3 as it was computed by doing t e+ e-, but the measurement has all leptons (e, mu and tau).

**Comment by giacomomagni** [comment]
Hi @LucaMantani, 
thanks for reporting this problem.
We will try to address this issue providing a sanity check on all the available dataset see [here](https://github.com/LHCfitNikhef/smefit_release/issues/43). If I remember correctly there were also other datasets affected by these sort of problems like `4t` and `2t2b`

**Comment by giacomomagni** [comment]
Do I understand that this has been solved @jacoterh ?

**Comment by jacoterh** [comment]
This has been fixed in the updated tables, should be fixed automatically once we merge those.
